name: eshop
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  iconsax_flutter: ^1.0.0
  get: ^4.6.6
  flutter_snake_navigationbar: ^0.6.1
  badges: ^3.1.2
  carousel_slider: ^4.0.0
  http: ^1.2.1
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_fortune_wheel: ^1.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  test: ^1.25.2

flutter:

  uses-material-design: true

  #------------local asesset--------------#
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/